### PR TITLE
Merge pull request #10 from NetherlandsForensicInstitute/document-how…

### PR DESCRIPTION
**Pull request by rdvdijk**
Fixes some code style issues in `kaitai_utils.py`.

### CODE REVIEW

**Comment by rdvdijk** [comment]
```sh
pip install flake8
flake8 --max-line-length 120 kaitai_utils.py
```

**Review by eoudsen — APPROVED** [review]
LGTM

**Review by Carly-1 — APPROVED** [review]
Nice!

**Comment by rdvdijk** [comment]
I did something strange, apparently I amended the previous merge commit?! My bad, I'll create a fresh PR.

**Comment by rdvdijk** [comment]
> I did something strange, apparently I amended the previous merge commit?! My bad, I'll create a fresh PR.

See new PR: #12

**Pull request closed without merging**
